
<div class="main-content-box">



    <h2>Thông số kỹ thuật lốp xe</h2>



    <div class="items-list-prod">


        <div class="wrap_detail">
            
            <p class="fs14 fwb upper">Tầm quan trọng của lốp</p>

            <p class="mt5">Nói một cách đơn giản là xe không thể di chuyển khắp nơi nếu không có lốp xe, do vậy lốp xe là một trong những thành phần quan trọng nhất bảo đảm cho sự vận hành an toàn của bạn.</p>

            <div class="wrap_lx_tab">
                <ul>
                    <li><a class="lx_1" href="javascript:void(0);" title="">Chức năng của lốp xe</a></li>
                    <li><a class="lx_2" href="javascript:void(0);" title="">Cách đọc các thông số trên hông lốp</a></li>
                </ul>

                <div class="clearAll">&nbsp;</div>

                <div class="wrap_tab_content wrap_lx_tab_content">
                    <div class="tab_content" style="display: block;"><img alt="thông số lốp xe ô tô" src="<?php echo BASE_URL ?>/public/images/lx_img_1.jpg"></div>

                    <div class="tab_content" style="display: none;">
                        <div class="lx_tab_left left"><img alt="thong so lop xe" src="<?php echo BASE_URL ?>/public/images/lx_img_2.jpg"></div>

                        <div class="lx_tab_right left">
                            <p class="lx_tab_title">Hiểu rõ các thông số của lốp xe sẽ giúp bạn có những kiến thức căn bản về lốp xe cũng như cách lựa chọn lốp xe phù hợp:</p>

                            <p>1. 205: Chiều rộng mặt lốp (mm).</p>

                            <p>2. 55: Tỉ lệ cho biết chiều cao của hông lốp, được đo như là tỷ lệ phần trăm của chiều rộng của nó. 55% chỉ đơn giản là 55% của 205 mm (=112,75mm)</p>

                            <p>3. R: Cấu trúc bố thép, loại lốp xe thông dụng nhất hiện nay</p>

                            <p>4. 16: Đường kính mâm xe (inches; 1 inches = 25.4 mm)</p>

                            <p>5. 91: Chỉ số tải trọng (LI), cho biết tải trọng tối đa cho phép. A 91 LI chỉ tải trọng tối đa cho phép là 615kg</p>

                            <p>6. V: Chỉ số tốc độ (SS). Chỉ số tốc độ tối đa cho phép. Ký hiệu "H" là chỉ số tốc độ thông thường, ký hiệu "V", "Z" là các chỉ số tốc độ cao</p>
                        </div>

                    <div class="clearAll">&nbsp;</div>

                    <div >
                <p class="fs14 fwb upper">So sánh lốp bố kẽm vs lốp bố nylon</p>
                     <p>So sánh giữa 2 loại lốp cơ bản (Radial - Lốp xe có các lớp bố hướng tâm và Bias - Lốp xe có các lớp bố chéo nhau), lốp Radial vượt trội hơn lốp Bias cả về tính kinh tế, sự an toàn &amp; tính năng 1 cách rõ rệt.</p>

                    <img src="<?php echo BASE_URL ?>/public/images/ss1.jpg" alt="">
                    <img src="<?php echo BASE_URL ?>/public/images/ss2.jpg" alt="">            
                    <div class="clearAll"></div>
                
            </div>
            <div class="faq">
                <table border="1" width="100%">
                    <tbody>
                    <tr>
                    <td width="84">
                                    <strong>TIÊU CHÍ</strong>
                                </td>
                    <td width="60">
                                    <strong>&nbsp;</strong>
                                </td>
                    <td width="408">
                                    <strong>LỐP BỐ KẼM </strong>(Lốp Radial)
                                </td>
                    <td width="132">
                                    <strong>LỐP NILON </strong>(Lốp bias, lốp mành chéo)
                                </td>
                    </tr>
                    <tr>
                    <td rowspan="4" width="84">
                                    <strong>Tuổi thọ lốp</strong>
                    </td>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Độ bền cao gấp hai lần lốp bias. Đối với một chiếc xe chở hàng 50,000 km còn&nbsp; xe sử dụng lốp bố nylon là 24,000 (vỏ bridgestone)
                    <p>
                                        Đối với xe bus liên tỉnh sử dụng lốp bố kẽm Việt Trade có quãng đường đi được là 100,000 km còn xe sử dụng lốp bố nylon là 45,000 km
                                    </p>
                    </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    <strong><em>Lý do</em></strong>
                                </td>
                    <td colspan="2" width="540">
                                    Với lốp bố kẽm, mặt lốp ít biến dạng, thoát nhiệt nhanh hơn, áp lực tiếp xúc đồng đều làm cho việc chống mòn lốp tốt hơn. Sinh nhiệt thấp, thoát nhiệt tốt hơn
                    <p>
                                        Với lốp nilon, do tầng vải đặt chéo góc nhau, gây ma sát lớn, sinh nhiệt nhiều
                                    </p>
                    </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td colspan="2" width="540">
                                    Bố nilon có hông lốp dày nên khi chuyển động sẽ sinh nhiều nhiệt lượng. Bố kẽm chỉ cấu tạo từ một hoặc hai lớp sợi song song nhau nên hông lốp mỏng và có khả năng chịu uốn, gấp rất tốt. Do đó lốp radial chạy nguội hơn
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Mặt lốp có thể dán lại nhiều lần ???
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td rowspan="2" width="84">
                                    <strong>Tiêu thụ nhiên liệu</strong><strong>&nbsp;</strong>
                    </td>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Tiết kiệm nhiên liệu hơn vỏ nilon từ 10 – 16% (trong điều kiện Việt Nam)
                                </td>
                    <td width="132">
                                    Tốn nhiên liệu hơn
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    <strong><em>Lý do</em></strong>
                                </td>
                    <td colspan="2" width="540">
                                    Đã được kiểm tra thực tế. Tiêu hao nhiên liệu thấp do giảm ma sát trên mặt đường, kháng lăn thấp
                                </td>
                    </tr>
                    <tr>
                    <td rowspan="2" width="84">
                                    <strong>Tải trọng</strong>
                                </td>
                    <td width="60">
                                    <strong><em>&nbsp;</em></strong>
                                </td>
                    <td width="408">
                                    Chịu tải tốt hơn
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    <strong><em>Lý do</em></strong>
                                </td>
                    <td colspan="2" width="540">
                                    Khung lốp bền vững giúp xe chịu tải tốt hơn
                                </td>
                    </tr>
                    <tr>
                    <td rowspan="7" width="84">
                                    <strong>An toàn</strong><strong>&nbsp;</strong>
                    </td>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Điều khiển dễ dàng hơn, bám đường tốt hơn và lượng mài mòn ít hơn, hạn chế mài mòn không đều
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    <strong><em>Lý do</em></strong>
                                </td>
                    <td colspan="2" width="540">
                                    Tầng hoãn xung của lốp radian là sợi thép (còn gọi là bố thép) nằm gần như song song với hướng chu vi của lốp có tác dụng bảo đảm mặt lốp không bị biến dạng trong quá trình lốp lăn trên mặt đường, do đó lốp bám đường tốt hơn, ít bị mòn hơn và đáp ứng điều khiển của người lái tốt hơn
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Không bị xẹp hay nổ bất thình lình, gây tai nạn giao thông, đặc biệt khi chạy tốc độ cao trên mặt đường tốt. Không bị mất áp lực đột ngột và không phải dừng xe thay lốp mỗi khi cán phải đinh hoặc vật nhọn
                    <p>
                                        Chiều cao mặt cắt lốp thấp, lốp vững chắc hơn, đáp ứng nhanh khi bẻ lái, an toàn hơn
                                    </p>
                    </td>
                    <td width="132">
                                    Có ruột, xì hơi nhanh, kém an toàn
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Chống đâm thủng tốt do có lớp đai thépHạn chế mài mòn không đều
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Lực cản lăn thấp cho phép xe chạy ổn định ở tốc độ cao
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Giảm chấn tốt, vận hành êm, gia tốc nhạy cảm, hiệu suất phanh hãm cao cho phép xe chạy ở tốc độ cao nhưng rất ổn định
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Hãm thắng tốt hơn khi đường ướt
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="84">
                                    <strong>Sử dụng</strong>
                                </td>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Lốp nhẹ hơn, thuận lợi hơn khi lắp ráp
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="84">
                                    <strong>Giá cả</strong>
                                </td>
                    <td width="60">
                                    &nbsp;
                                </td>
                    <td width="408">
                                    Với những ưu điểm như trên nhưng giá chỉ hơn từ……% đến …….%
                                </td>
                    <td width="132">
                                    &nbsp;
                                </td>
                    </tr>
                    <tr>
                    <td width="84">
                                    <strong>Đánh giá chung</strong>
                                </td>
                    <td colspan="3" width="600">
                                    Trong điều kiện cơ sở hạ tầng ngày càng được đầu tư lớn, cầu đường tốt hơn thì các ưu điểm trên càng thể hiện rõ. Điều này cũng phù phù hợp với tình trạng của các nước phát triển.
                                </td>
                    </tr>
                    </tbody>
                    </table>
                </div>
                            
        </div>

                    </div>
                </div>
            </div>
            <div class="clearAll"></div>



    </div>



</div>

<script type="text/javascript">
    //tab
        if($('.wrap_tab .tabs_ li a').length > 0){
            $('.wrap_tab .tabs_ li a').first().addClass('active');
            $('.wrap_tab .tabs_ li a').click(function(){
                var index = $(this).parent().index();
                $('.wrap_tab .tabs_ li a').removeClass('active');
                $(this).addClass('active');
                $('.wrap_tab_content .tab_content').hide();
                $('.wrap_tab_content .tab_content').eq(index).show();
            });
            if($('#box_lbat').length>0){
                $('.wrap_tab .tabs_ li a:eq(2)').trigger('click');
            }
        }
        //tab 2
        if($('.wrap_lx_tab ul li a').length > 0){
            $('.wrap_lx_tab ul li a').first().addClass('active');
            $('.wrap_lx_tab ul li a').click(function(){
                var index = $(this).parent().index();
                $('.wrap_lx_tab ul li a').removeClass('active');
                $(this).addClass('active');
                $('.wrap_tab_content .tab_content').hide();
                $('.wrap_tab_content .tab_content').eq(index).show();
            });
        }
</script>

<style type="text/css">
.fwb {
    font-weight: bold;
}
.upper {
    text-transform: uppercase;
}
.wrap_detail {
    color: #fff;
}
.wrap_lx_tab {
    margin-top: 27px;
}
ul {
    list-style: none;
    padding: 0;
}
.wrap_lx_tab ul li {
    float: left;
}

li {
    display: list-item;
}
.wrap_lx_tab ul li a:hover, .wrap_lx_tab ul li a.active {
    background-color: #bcbec0;
}
.wrap_lx_tab ul li a.lx_1 {
    background: #bcbec0 url(../public/images/lx_tab_icon_1.png) 17px 9px no-repeat;
}
.wrap_lx_tab ul li a {
    display: block;
    height: 34px;
    padding: 0 57px 0 37px;
    font-size: 16px;
    color: #000;
    line-height: 35px;
}
.wrap_lx_tab ul li a.lx_2 {
    background: #bcbec0 url(../public/images/lx_tab_icon_2.png) 13px 9px no-repeat;
}
.wrap_lx_tab_content {
    margin-top: 0;
    width: auto;
    background: #bcbec0;
}
.wrap_tab_content {
    color: #000;
    width: 100%;
    background: url(../public/images/tab_bg.png) center 0 no-repeat;
}
.wrap_tab_content .tab_content:first-child {
    display: block;
}
.wrap_lx_tab_content .tab_content {
    padding: 0;
    background: #fff;
}
.wrap_tab_content .tab_content {
    display: none;
    clear: both;
    padding: 0 15px;
    padding-top: 20px;
    min-height: 125px;
}
img {
    border: 0px;
}
img {
    color: transparent;
    font-size: 0;
    vertical-align: middle;
    -ms-interpolation-mode: bicubic;
}
.wrap_lx_tab ul li a:hover, .wrap_lx_tab ul li a.active {
    background-color: #fff;
}
.lx_tab_left {
    width: 253px;
    text-align: center;
    padding-top: 20px;
    padding-bottom: 23px;
}
.lx_tab_right {
    width: 372px;
    padding-bottom: 23px;
}
.left {
    float: left;
}
.clearAll {
    clear: both;
    font-size: 0px;
    width: 0px;
    height: 0px;
}
</style>