<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">



<html xmlns="http://www.w3.org/1999/xhtml"  xml:lang="vi-vn" lang="vi-vn">



<head prefix=



    "og: http://ogp.me/ns# 



     fb: http://ogp.me/ns/fb# 



     product: http://ogp.me/ns/product#">



      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />







      <title><?php echo isset($title) ? $title : null ?>Lốp xe giá rẻ, vỏ xe giá rẻ, lốp xe tải, lốp xe container, vỏ xe ôtô</title>



      <meta name="description" content="Trung tâm Lốp xe chính hãng - đại lý vỏ xe ôtô, xe tải, container, xe ben, xe khách chất lượng giá rẻ nhất, nhập khẩu trực tiếp từ nhà máy Thái Lan, Ấn Độ, Trung Quốc.Viet-Trade.ORG" />



      <meta name="keywords" content="Lốp xe, lop xe, lốp xe chính hãng, lop xe chinh hang, lop xe gia re, lop xe oto tai, lop xe container, lop xe ben, vo xe tai, vỏ xe ôtô, vo xe o to, lốp xe trung quốc, lốp xe thái lan, lốp xe ấn độ, lop xe trung quoc, lop xe thai lan, lop xe an do" />







      <link rel="shortcut icon" href="<?php echo BASE_URL ?>/public/img/favicon.ico" type="image/x-icon" />



      <base href="<?php echo BASE_URL ?>" />



      <link rel="canonical" href="<?php echo BASE_URL ?>" />







      <meta name="generator" content="<?php echo BASE_URL ?>"  />







     <meta name="robots" content="index,follow" />



     <meta name="revisit-after" content="0 days" />



     <meta name="distribution" content="global" />



     <meta name="search engine" content="www.google.com, www.google.com.vn, www.google.co.uk, www.google.it, www.google.es, www.google.com.au, www.altaVista.com, www.aol.com, www.infoseek.com, www.excite.com, www.hotbot.com, www.lycos.com, www.magellan.com, www.cnet.com, www.voila.com, www.google.fr, www.yahoo.fr, www.yahoo.com, www.alltheweb.com, www.msn.com, www.netscape.com, www.nomade.com" />



     <meta name="author" content="Việt Trade" />



     <meta name="copyright" content="Việt Trade" />



     <meta name="all" content="index,follow" />



     <meta name="rating" content="general" />



     <meta name="googlebot" content="index,follow" />



     <meta name="DC.title" content="29, QL 51, Phước Tân, Biên Hòa, Đồng Nai, Vietnam" />



     <meta name="geo.region" content="VN-Hồ Chí Minh" />



     <meta name="geo.placename" content="29, QL 51, Phước Tân, Biên Hòa, Đồng Nai, Vietnam" />



     <meta name="geo.position" content="10.7999680;106.6401140" />



     <meta name="ICBM" content="10.7999680;106.6401140" />











      <meta property="og:site_name" content="Lốp xe" />



      <meta property="og:image" content="<?php echo BASE_URL ?>/public/images/logo-viet-trade.png" />



      <meta property="og:title" content="Lốp xe giá rẻ, vỏ xe giá rẻ, lốp xe tải, lốp xe container, vỏ xe ôtô" />



      <meta property="og:description" content="Trung tâm Lốp xe chính hãng - đại lý vỏ xe ôtô, xe tải, container, xe ben, xe khách chất lượng giá rẻ nhất, nhập khẩu trực tiếp từ nhà máy Thái Lan, Ấn Độ, Trung Quốc.Viet-Trade.ORG" />



      <meta property="og:url" content="<?php echo BASE_URL ?>" />



      <meta property="og:type" content="article" />



      <meta property="fb:admins" content="100006939935903" />



      <meta property="fb:app_id" content="1444772099185572" />







<script type="text/javascript">



  var base_url="<?php echo BASE_URL ?>";



  var current_id_buy_now=0;



  var checkOutUrl="thanh-toan/step-1";



</script>











  <meta name="viewport" content="width=device-width, initial-scale=1">



  <!--alexa-->



  



  <link rel="stylesheet" href="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/css/bootstrap.min.css">



  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">



  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>



  <script src="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/js/bootstrap.min.js"></script>



 <!-- <script src="<?php ?>/style/frontend/theme/default/js/jquery-ui.js"></script> -->



  <link rel="stylesheet" href="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/css/custom.css">



        <link rel="stylesheet" href="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/css/responsive.css">



    <style>



    .content-detail img{max-width:800px;}



  </style>



  



  <script src="<?php echo BASE_URL ?>/public/js/custom.js"></script>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76797448-1', 'auto');
  ga('send', 'pageview');

</script>



</head>







<body>



  <header>



    <div class="top-panel-fixed-wrp">



      <div class="container top-panel-fixed">



        <div class="col-lg-3 col-md-4 col-sm-12 col-sm-12 main-menu-fixed"></div>



        <div class="col-lg-7 col-md-6 col-sm-12 col-xs-12 search-top-fixed"></div>



        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 cart-fixed dropdown" id="cartTopRightFix"></div>



      </div>



    </div>







    <nav class="navbar navbar-default top-panel">



      <div class="container">



          <ul class="nav navbar-nav navbar-right">



            <li><a href="<?php echo BASE_URL ?>/" title="Lốp xe chính hãng chất lượng giá tốt nhất thị trường">Trang chủ</a></li>



            <li><a href="<?php echo BASE_URL ?>/vn/giao-nhan-hang" title="Lốp xe chính hãng chất lượng giá tốt nhất thị trường giao nhận hàng">Giao hàng</a></li>



            <li><a href="<?php echo BASE_URL ?>/vn/huong-dan-mua-hang" title="Hướng dẫn mua hàng">Hướng dẫn</a></li>



            <li><a href="<?php echo BASE_URL ?>/vn/tu-van" title="Tư vấn">Tư vấn</a></li>



            <li><a href="<?php echo BASE_URL ?>/vn/gioi-thieu" title="Giới thiệu Lốp xe chính hãng chất lượng giá tốt nhất thị trường">Giới thiệu</a></li>



            <li><a href="<?php echo BASE_URL ?>/vn/lien-he" title="Liên hệ Lốp xe chính hãng chất lượng giá tốt nhất thị trường">Liên hệ</a></li>



            <?php if (isset($_SESSION['user_logined'])) { ?>



            <li><a data="admin" href="<?php echo $this->url('admin') ?>">Quản trị</a></li>



            <?php } ?>



            <?php 



            if ($_SESSION) {



              ?>



              <li><a class="logined" href="<?php echo BASE_URL.'/user/info/'.$_SESSION['userid_logined'] ?>"><b><i><?php echo $_SESSION['user_logined']; ?> </i></b></a> </li>



              <li><a class="logined" href="<?php echo $this->url('user/logout') ?>">Logout</a></li>



              <?php



            }



            else{



              ?>



              <li><a class="logined" href="<?php echo $this->url('user/login') ?>">Login</a></li>



              <?php



            }



            ?>



          </ul>



        </div>



    </nav>



    



    <div class="container">



      <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 logo">



        <h1>



          <a href="<?php echo BASE_URL ?>" title="Lốp xe">



            <img src="<?php echo BASE_URL ?>/public/images/logo-viet-trade.png" alt="Lốp xe" width="220" height="61" />



          </a>



        </h1>



      </div>







      <div class="col-lg-7 col-md-6 col-sm-12 col-xs-12 search-top">



        <form role="form" action="<?php echo BASE_URL ?>/vn/tim-kiem" method="post">



            <div class="form-group">



              <div class="col-md-11 col-sm-11 col-xs-11 search-col"><input name="txtHeaderSearch" type="text" class="form-control" id="search" placeholder="Nhập tên sản phẩm muốn tìm..." value=""></div>



              <div class="col-md-1 col-sm-1 col-xs-1 search-col"><button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button></div>



            </div>



            <div class="suggested-search">Nhiều người tìm kiếm: 



              <a href="<?php echo BASE_URL ?>/vn/lop-xe-bo-kem" title="Lốp xe bố kẽm">Lốp xe bố kẽm</a>



            <a href="<?php echo BASE_URL ?>/vn/lop-xe-cao-cap" title="Lốp xe cao cấp">Lốp xe cao cấp</a>    



              <a href="<?php echo BASE_URL ?>/vn/lop-xe-gia-re" title="Lốp xe giá rẻ">Lốp xe giá rẻ</a>   



              <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai" title="Lốp xe tải">Lốp xe tải</a>
              <a href="<?php echo BASE_URL ?>/vn/vo-xe-oto" title="Vỏ xe ôtô">Vỏ xe ôtô</a>
            </div>



        </form>



      </div>



       <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 cart-top dropdown" id="cartTopRight">



          <div class="dropdown-toggle" data-toggle="dropdown">



            <div class="cart-top-right cartTopRightQuantity">0</div>



          </div>



                  



          <ul class="dropdown-menu cartTopRightContent">



            <li>



              <div class="col-md-12 item-cart">



                Bạn chưa chọn sản phẩm nào!



              </div>



            </li>



          </ul>



      </div>



    </div>



  </header>



  



  <section><!-- begin main content -->



    <div class="container main-content">



      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 col-left-ct">



        <div class="col-lg-3 col-md-4 col-sm-12 col-sm-12 main-menu">



          <div class="header-main-menu"><i class="fa fa-bars"></i>Danh mục sản phẩm</div>



          <ul class="main_menu_dropdown">



            <li class="hadsub-menu">



              <a class="menu-link" href="<?php echo BASE_URL ?>/vn/lop-xe-bo-kem" title="Lốp xe bố kẽm"><i class="menu-01"></i><h2>Lốp xe bố kẽm</h2> </a>



              <span></span>



            </li>



            <li class="hadsub-menu">



              <a class="menu-link" href="<?php echo BASE_URL ?>/vn/lop-xe-bo-nylon" title="Lốp xe bố nylon"><i class="menu-02"></i><h2>Lốp xe bố nylon</h2> </a>



              <span></span>



            </li>



            <li class="hadsub-menu">



              <a class="menu-link" href="<?php echo BASE_URL ?>/vn/lop-xe-co-ruot" title="Lốp xe có ruột"><i class="menu-03"></i><h2>Lốp xe có ruột</h2> </a>



              <span></span>



            </li>



            <li class="hadsub-menu">



              <a class="menu-link" href="<?php echo BASE_URL ?>/vn/lop-xe-khong-ruot" title="Lốp xe không ruột"><i class="menu-04"></i><h2>Lốp xe không ruột</h2> </a>



              <span></span>



            </li>



            <li class="hadsub-menu">



              <a class="menu-link" href="<?php echo BASE_URL ?>/vn/lop-theo-loai-xe" title="Lốp theo loại xe"><i class="menu-05"></i><h2>Lốp theo loại xe</h2> <i class="fa fa-angle-right"></i></a>



              <span></span>



              <ul class="submenu-lv1">



                <li>



                  <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai" title="Lốp xe tải và bus">Lốp xe tải và bus</a>



                    <ul class="submenu-lv2">



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe khách dưới 16 chỗ" title="Xe khách dưới 16 chỗ">Xe khách dưới 16 chỗ</a>



                      </li>



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe khách dưới 34 chỗ" title="Xe khách dưới 34 chỗ">Xe khách dưới 34 chỗ</a>



                      </li>



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe khách từ 40 chỗ" title="Xe khách từ 40 chỗ">Xe khách từ 40 chỗ</a>



                      </li>



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe tải dưới 1.2 tấn" title="Xe tải dưới 1.2 tấn">Xe tải dưới 1.2 tấn</a>



                      </li>



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe tải nhẹ" title="Xe tải nhẹ">Xe tải nhẹ</a>



                      </li>



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe tải lớn" title="Xe tải lớn">Xe tải lớn</a>



                      </li>



                      <li>



                        <a href="<?php echo BASE_URL ?>/vn/lop-xe-tai?Xe container" title="Xe container">Xe container</a>



                      </li>



                    </ul>



                  </li>



                  <li>



                    <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich" title="Lốp xe ôtô du lịch">Lốp xe ôtô du lịch</a>



                      <ul class="submenu-lv2">



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Sedan" title="Sedan">Sedan</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Coupe" title="Coupe">Coupe</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?SUV" title="SUV">SUV</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?MPV" title="MPV">MPV</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Mini Van" title="Mini Van">Mini Van</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Hatchback" title="Hatchback">Hatchback</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Convertible" title="Convertible">Convertible</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Spyder" title="Spyder">Spyder</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?CUV" title="CUV">CUV</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Limosine" title="Limosine">Limosine</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-du-lich?Pick-up" title="Pick-up">Pick-up</a>



                        </li>



                      </ul>



                  </li>



                  <li>



                    <a href="<?php echo BASE_URL ?>/vn/lop-xe-dac-chung" title="Lốp xe đặc chủng">Lốp xe đặc chủng</a>



                      <ul class="submenu-lv2">



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-dac-chung?Xe công nghiệp" title="Xe công nghiệp">Xe công nghiệp</a>



                        </li>



                        <li>



                          <a href="<?php echo BASE_URL ?>/vn/lop-xe-dac-chung?Xe nông nghiệp" title="Xe nông nghiệp">Xe nông nghiệp</a>



                        </li>



                      </ul>



                  </li>



                  <li>



                    <a href="<?php echo BASE_URL ?>/vn/lop-xe" title="Lốp xe khác">Các loại khác</a>



                  </li>



                  <li></li>



                </ul>



              </li>



              <li class="hadsub-menu">



                <a class="menu-link" href="<?php echo BASE_URL ?>/vn/lop-theo-hang-san-xuat" title="Lốp theo hãng sản xuất"><i class="menu-06"></i><h2>Lốp theo hãng sản xuất</h2> </a>



                <span></span>



              </li>



          </ul>



        </div>



        <div class="col-lg-9 col-md-8 col-sm-12 col-xs-12 main-slider">



          <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">



            <!-- Indicators -->



            <!-- <ol class="carousel-indicators">



              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>



            </ol> -->







            <!-- Wrapper for slides -->



            <div class="carousel-inner" role="listbox">



              <div class="item active">



                <a href="<?php echo BASE_URL ?>/vn/san-pham" title="Lốp xe chính hãng chất lượng giá rẻ nhất thị trường">



                  <img src="<?php echo BASE_URL ?>/public/images/banner-lopxe.jpg" alt="Lốp xe chính hãng chất lượng giá rẻ nhất thị trường">



                </a>



              </div>



              <div class="item">



                <a href="<?php echo BASE_URL ?>/vn/san-pham" title="Lốp xe chính hãng chất lượng giá rẻ nhất thị trường">



                  <img src="<?php echo BASE_URL ?>/public/images/banner-lopxe-2.jpg" alt="Lốp xe chính hãng chất lượng giá rẻ nhất thị trường">



                </a>



              </div>



            </div>



          </div>



        </div>







        <div class="col-lg-12 col-md-12 content">



            <?php echo $content ?>



        </div>







      </div>







      <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 col-right-ct">        



        <div class="suport-box">



          <div class="info-title">Trung tâm lốp xe chính hãng</div><!-- h1 home page only -->



          <div class="hotline"><i class="fa fa-phone"></i>  <span>0931.557.775 </span><span>0931.55.99.09</span> <div class="clearFix"></div></div>



          <div class="info">29, QL 51, Phước Tân, Biên Hòa, Đồng Nai</div>  



          <div class="info maps-link"><a href="<?php echo BASE_URL ?>/vn/ban-do" title="Xem bản đồ"><i class="fa fa-map-marker"></i>Xem bản đồ</a></div> 



          <div class="info work-time">Giờ làm việc: Từ 7g30 - 17g00 <br>(Cả Thứ 7 & CN)</div> 



        </div>    



        <div class="content-box home-products">



          <h2>Quan tâm nhiều</h2>



          <div class="items-list-ctb">

          <?php if(isset($tire_product_features)){ ?>

            <?php foreach ($tire_product_features as $tire_product_feature) { ?>



            <div class="items-ctb">



              <div class="img-ctb">



                <a href="<?php echo BASE_URL ?>/vn/detail/<?php echo $tire_product_feature->tire_product_link ?>" title="Lốp xe <?php echo $tire_product_feature->tire_producer_name.' '.$tire_product_feature->tire_product_size_number.' '.$tire_product_feature->tire_product_name ?>">

                  <img src="<?php echo BASE_URL ?>/public/images/upload/<?php echo $tire_product_feature->tire_product_thumb ?>" alt="Lốp xe <?php echo $tire_product_feature->tire_producer_name.' '.$tire_product_feature->tire_product_size_number.' '.$tire_product_feature->tire_product_name ?>" />

                </a>



              </div>



              <div class="title-ctb">



                <a href="<?php echo BASE_URL ?>/vn/detail/<?php echo $tire_product_feature->tire_product_link ?>" title="Lốp xe <?php echo $tire_product_feature->tire_producer_name.' '.$tire_product_feature->tire_product_size_number.' '.$tire_product_feature->tire_product_name ?>">Lốp xe <?php echo $tire_product_feature->tire_producer_name.' '.$tire_product_feature->tire_product_size_number.' '.$tire_product_feature->tire_product_name ?></a>



              </div>



              <div class="price-ctb price-ctb-old"><?php echo $lib->formatMoney(round($tire_product_feature->tire_retail*1.07)) ?> đ</div>



              <div class="price-ctb"><?php echo $lib->formatMoney($tire_product_feature->tire_retail) ?> đ</div>



                                                



              <div class="clearFix"></div>



            </div>



            <?php } ?>



            <?php } ?>



          </div>



        </div>

        <!-- <div class="content-box home-products">
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          AD
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-8303573181078043"
               data-ad-slot="9081990219"
               data-ad-format="auto"></ins>
          <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
        </div> -->



      </div>







    </div>



  </section>







﻿  <footer>



    <div class="container">



      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12 footer-link">



        <ul>



          <li class="header-fl"><h3>CHĂM SÓC KHÁCH HÀNG</h3></li>



          <li><a href="<?php echo BASE_URL ?>/vn/thong-tin-thanh-toan" title="Thanh toán"><i class="fa fa-caret-right"></i>Thanh toán</a></li>



          <li><a href="<?php echo BASE_URL ?>/vn/huong-dan-mua-hang" title="Hướng dẫn mua hàng"><i class="fa fa-caret-right"></i>Hướng dẫn mua hàng</a></li>



          <li><a href="<?php echo BASE_URL ?>/vn/giao-nhan-hang" title="Giao hàng & Nhận hàng"><i class="fa fa-caret-right"></i>Giao hàng & Nhận hàng</a></li>



        </ul>



        <div class="clearFix"></div>



      </div>



      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12 footer-link">



        <ul>



          <li class="header-fl"><h3>Giới thiệu</h3></li>



          <li><a href="<?php echo BASE_URL ?>/vn/gioi-thieu" title="Về chúng tôi"><i class="fa fa-caret-right"></i>Về chúng tôi</a></li>



          <li><a href="<?php echo BASE_URL ?>/vn/lien-he" title="Liên hệ"><i class="fa fa-caret-right"></i>Liên hệ</a></li>



          <li><a href="<?php echo BASE_URL ?>/vn/thong-so-lop" title="Thông số lốp"><i class="fa fa-caret-right"></i>Thông số lốp</a></li>



        </ul>



        <div class="clearFix"></div>



      </div>



      <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12 footer-link">



        <ul>



          <li class="header-fl"><h3>Sản phẩm nổi bật</h3></li>



          <li><a href="<?php echo BASE_URL ?>/vn/lop-xe-moi-nhat" title="Lốp xe mới nhất">Lốp xe mới nhất</a></li>



          <li><a href="<?php echo BASE_URL ?>/vn/lop-xe-khuyen-mai" title="Lốp xe khuyến mãi">Lốp xe khuyến mãi</a></li>



          <li><a href="<?php echo BASE_URL ?>/vn/dai-ly-lop-xe" title="Đại lý lốp xe">Đại lý lốp xe</a></li>



        </ul>



        <div class="clearFix"></div>



      </div>



      <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 footer-link social-link">



        <ul>



          <li class="header-fl"><h3><i class="fa fa-share-alt"></i> Cộng đồng</h3></li>



          <li class="social-icon">



            <span>



              <a target="_blank" rel="nofollow" href="https://www.facebook.com/VietTrade.org" title="Lốp xe chính hãng"><img src="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/images/fb_icon.jpg" alt="Lốp xe chính hãng"/></a>



            </span>



            <span>



              <a target="_blank" href="https://plus.google.com/105337392415927459152" title="Trung tâm phân phối lốp xe" rel="publisher"><img src="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/images/gplus_icon.jpg" alt="Trung tâm phân phối lốp xe"/></a>



            </span>



            <span>



              <a target="_blank" rel="nofollow" href="https://www.youtube.com/channel/UCiCfyccqhkC9meRDxZXGYQA" title="Youtube"><img src="<?php echo BASE_URL ?>/public/theme/style/frontend/theme/default/images/youtube_icon.jpg" alt="Youtube"/></a>



            </span>



          </li>







        </ul>



        <div class="clearFix"></div>



      </div>



    </div>



    <div class="copyright">



      <div class="container">Copyright ©<?php echo date('Y') ?> <a href="<?php echo BASE_URL ?>" title="Việt Trade">Việt Trade</a>. All rights reserved.</a>
        <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>
      </div>



    </div>



  </footer>







<!-- popup content -->



<!-- end popup content -->







<!-- popup content -->



<script type="text/javascript" src="<?php echo BASE_URL ?>/public/theme/javascript/jquery.lightbox_me.js"></script>



<script type="text/javascript" src="<?php echo BASE_URL ?>/public/theme/javascript/jquery.cookie.js"></script>







<script  type="text/javascript">



         function popup(){



      $('.window_popup').lightbox_me({



      centered: true,



      });



      e.preventDefault();



      $ele.trigger('close');



    }               



        $(document).ready(function() {



            if($.cookie('showOnlyOne')){



        // nothing to do



            } else {



                $.cookie('showOnlyOne', 'showOnlyOne', { expires: 1 });



        popup() // get popup



            }



        });



        </script>



<!-- end popup content -->











    







<div id="fb-root"></div>



  



  <script src="<?php echo BASE_URL ?>/public/theme/javascript/tmd/index.js"></script>







  <!-- sign up / sign in popup !-->







  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/theme/javascript/tmd/frontend.js"></script>



  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/theme/javascript/tmd/tmd.js"></script>



  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/theme/javascript/tmd/lib.js"></script>



  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/theme/javascript/tmd/cart.js"></script>



  

<style type="text/css">

.hisella-messages { position: fixed; bottom: 0; right: 0; z-index: 999999; }

.hisella-messages-outer { position: relative; }

#hisella-minimize { background: #3b5998; font-size: 14px; color: #fff; padding: 3px 10px; position: absolute; top: -34px; left: -1px; border: 1px solid #E9EAED; cursor: pointer; }

@media screen and (max-width:768px){ #hisella-facebook { opacity:0; } .hisella-messages { bottom: -300px; right: -135px; } }

</style>

<div id='fb-root'></div>

<script>

(function($) { $(document).ready(function(){ $( '#hisella-minimize' ).click( function() { if( $( '#hisella-facebook' ).css( 'opacity' ) == 0 ) { $( '#hisella-facebook' ).css( 'opacity', 1 ); $( '.hisella-messages' ).animate( { right: '0' } ).animate( { bottom: '0' } ); } else { $( '.hisella-messages' ).animate( { bottom: '-300px' } ).animate( { right: '-135px' }, 400, function(){ $( '#hisella-facebook' ).css( 'opacity', 0 ) } ); } } ) }); })(jQuery);

(function(d, s, id) {



  var js, fjs = d.getElementsByTagName(s)[0];



  if (d.getElementById(id)) return;



  js = d.createElement(s); js.id = id;



  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";



  fjs.parentNode.insertBefore(js, fjs);



}(document, 'script', 'facebook-jssdk'));

</script>

<div class="hisella-messages"><div class="hisella-messages-outer"><div id="hisella-minimize">Facebook chat</div><div id="hisella-facebook" class='fb-page' data-adapt-container-width='true' data-height='300' data-hide-cover='false' data-href='https://www.facebook.com/VietTrade.org/' data-show-facepile='true' data-show-posts='false' data-small-header='false' data-tabs='messages' data-width='250'></div></div></div>





</body>



</html>

